server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MangKyu/spring-cloud-config-sample
          search-paths: test-cloud-config-file/**
          default-label: master